version: '3.0'

services:
  web:
    image: alexcheng/magento:latest
    ports:
      - "80:80"
    volumes:
      - ./app/etc/modules/Salesfire_Salesfire.xml:/var/www/html/app/etc/modules/Salesfire_Salesfire.xml:cached
      - ./app/design/frontend/base/default/layout/salesfire.xml:/var/www/html/app/design/frontend/base/default/layout/salesfire.xml:cached
      - ./app/code/community/Salesfire:/var/www/html/app/code/community/Salesfire:cached
      - ./lib/Salesfire:/var/www/html/lib/Salesfire:cached
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    ports:
      - "3306:3306"
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
